export type {
  AiFollowUpAction,
  AiQuery,
  Autoreply,
  BrandChannel,
  BrandEntity,
  BrandFormality,
  BrandIdentity,
  BrandIntelligence,
  BrandLocation,
  BrandMemory,
  BrandOffering,
  BrandPage,
  BrandPageStatus,
  BrandSourceRef,
  BrandVoice,
  BrandVoiceExample,
  ChannelProfile,
  ChannelStyle,
  CommunityPick,
  KeywordStrategyMapping,
  KeywordTargetEntry,
  MatchedAutoreply,
  ReplyContext,
  SearchStrategyEntry,
  SimulatedReply,
  SuggestedResource,
} from './types.ts';

export {
  BRAND_CHANNELS,
  defaultChannels,
  isAutoreply,
  isBrandEntity,
  isBrandOffering,
  isBrandPage,
  isBrandVoiceExample,
  isChannelMap,
  isChannelProfile,
  isCommunityPick,
  isRecord,
  isStringArray,
  migrateBrandEntity,
  migrateChannelMap,
} from './types.ts';

export {
  BrandClient,
  brandClient,
  type BrandClientOptions,
  type BrandIntelligenceInput,
} from './client.ts';

export {
  PROMPT_VERSION,
  buildAiQuery,
  buildBrandSystemPrompt,
  buildReplyContext,
  draftReply,
  extractBrandFromUrl,
  matchAutoreply,
  resolveSitemap,
  retrieveSourceRefs,
  seedSourcesFor,
  simulateOutbound,
  skippedBrand,
  suggestAcross,
  suggestKeywords,
  suggestResource,
  applyWebsiteFacts,
  websiteFactsSchema,
  siteMapSchema,
  type BrandQueryEvent,
  type WebsiteFacts,
  type SiteMap,
} from './helpers/index.ts';
